# This file was generated by GoReleaser. DO NOT EDIT.
class Playground < Formula
  desc "Useful toolset"
  homepage "https://github.com/peijiinsg/playground"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/peijiinsg/playground/releases/download/v1.0.1/playground_1.0.1_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "13ecba24eaeac5b6ba6db071dc3b008e127cfcd8ca2d7d615ff225c1a4ba4c20"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/peijiinsg/playground/releases/download/v1.0.1/playground_1.0.1_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "938bd5bec97bd720438d7a7b967f1a9673a1a7a6352086bc8da1246efc407161"
    end
  end

  def install
    # For some reason the tar ball that homebrew downloads contains another weirdly named 
    # tar ball that contains the actual files and needs to be extracted
    system("tar -xvf www.w3.org")
  end

  test do
    system "#{bin}/playground help"
  end
end
