# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Playground < Formula
  desc "Useful toolset"
  homepage "https://github.com/peijiinsg/playground"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/peijiinsg/playground/releases/download/v1.0.0/playground_1.0.0_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "3ec0ce014dcd7d3da054263314e6d1a241502bfcc53e421885d592111eaaab20"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/peijiinsg/playground/releases/download/v1.0.0/playground_1.0.0_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a9c9a13f6b3630a7d5569c9d588b2ae2eda2c22f2d2da07a9af94043c674c962"
    end
  end

  def install
    # For some reason the tar ball that homebrew downloads contains another weirdly named 
    # tar ball that contains the actual files and needs to be extracted
    system("tar -xvf www.w3.org")
  end

  test do
    system "#{bin}/playground help"
  end
end
