# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Playground < Formula
  desc "Useful toolset"
  homepage "https://github.com/peijiinsg/playground"
  version "1.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/peijiinsg/playground/releases/download/v1.1.2/playground_1.1.2_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "0d350388875ecdcd559b540cb3f0e0b1599101ea945521fe147069b8b156bfe1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/peijiinsg/playground/releases/download/v1.1.2/playground_1.1.2_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "79db515311e8233fabafb84b40d502418e18fd8998596b12edb8b5829faabb56"
    end
  end

  def install
    system("tar -xvf playground")
  end

  test do
    system "#{bin}/playground help"
  end
end
